apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "component.fullname" (dict "Release" .Release "Values" .Values.component.configMap) }}
  labels:
    {{ include "component.labels" (dict "Release" .Release "Values" .Values.component.configMap) | nindent 4 }}
data:
  APP_ENV: {{ .Values.component.configMap.APP_ENV | quote }}
  APP_DEBUG: {{ .Values.component.configMap.APP_DEBUG | quote }}
