apiVersion: v1
kind: Service
metadata:
  name: {{ include "component.fullname" (dict "Release" .Release "Values" .Values.component.frontend) }}
  labels:
    {{ include "component.labels" (dict "Release" .Release "Values" .Values.component.frontend) | nindent 4 }}
spec:
  type: {{ .Values.component.frontend.service.type }}
  selector:
    {{ include "component.selectorLabels" (dict "Release" .Release "Values" .Values.component.frontend) | nindent 4}}
  ports:
    - name: http
      port: {{ .Values.component.frontend.service.port }} 
      targetPort: {{ .Values.component.frontend.service.port }}