{{- if .Values.component.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "component.fullname" (dict "Release" .Release "Values" .Values.component.ingress) }}
  labels:
    {{ include "component.labels" (dict "Release" .Release "Values" .Values.component.ingress) | nindent 4 }}
  annotations:
    cert-manager.io/clusterIssuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.component.ingress.tls.hosts }}
      secretName: {{ .Values.component.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.component.ingress.rules.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "component.fullname" (dict "Release" .Release "Values" .Values.component.frontend) }}
                port: 
                  number: {{ .Values.component.frontend.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "component.fullname" (dict "Release" .Release "Values" .Values.component.backend) }}
                port:
                  number: {{ .Values.component.backend.service.port }}
{{- end }}
