apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 200
  template:
    spec:
      containers:
        - name: migrate
          image: "{{ .Values.component.backend.image.repository }}:{{ .Values.component.backend.image.tag }}"
          imagePullPolicy: {{ .Values.component.backend.image.pullPolicy }}
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: bmi-app-secret
      restartPolicy: Never