apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 200
  template:
    spec:
      containers:
        - name: migrate
          image: "{{ .Values.component.backend.image.repository }}:{{ .Values.component.backend.image.tag }}"
          imagePullPolicy: {{ .Values.component.backend.image.pullPolicy | default "IFNotPresent"}}
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: bmi-app-secret
      restartPolicy: Never